const fs = require("fs");

// Function to read an image file and convert it to a buffer
function imageToBuffer(filePath) {
  try {
    const image = fs.readFileSync(filePath);
    return Buffer.from(image);
  } catch (error) {
    console.error("Error reading image:", error);
    return null;
  }
}

const userData = [
  {
    username: "DrEmadShehab", // Unique username for the admin
    password: "Dr.Emad Shehab",
    Name: "Dr.Emad Shehab",
    Job: "Director",
    University: "Concordia University",
    Image: imageToBuffer("./photos/Dr-Emad-Shihab.jpg"),
    Website: "https://das.encs.concordia.ca/members/emad-shihab/",
    LinkedIn: "https://www.linkedin.com/in/emad-shihab-8099523/",
    Twitter: "https://twitter.com/EmadShihab",
    Email: "emad.shihab@concordia.ca",
  },
  {
    username: "LoriAkiyama", // Unique username for the admin
    password: "Lori Akiyama",
    Name: "Lori Akiyama",
    Job: "Program Coordinator",
    University: "Concordia University",
    Image: imageToBuffer("./photos/Lori-Akiyama.jpg"),
    LinkedIn: "https://www.linkedin.com/in/lori-akiyama/",
    Twitter: "",
    Website: "",
    Email: "lori.akiyama@concordia.ca",
  },
];
const userDataMembers = [
  {
    name: "Yiping Jia",
    username: "Yiping Jia",
    password: "Yiping Jia",
    University: "Queen's University",
    img: imageToBuffer("./photos/Yiping-Jia.jpg"),
    website: "",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Fangjian Lei",
    username: "Fangjian Lei",
    password: "Fangjian Lei",
    University: "Queen's University",
    img: imageToBuffer("./photos/Fangjian-Lei.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/fangjian-lei-5b110b204/",
    twitter: "",
    email: "",
  },
  {
    name: "Junjie Li",
    username: "Junjie Li",
    password: "Junjie Li",
    University: "Concordia University",
    img: imageToBuffer(".photos/Junjie-Li.jpg"),
    website: "",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Sharon Ho",
    username: "Sharon Ho",
    password: "Sharon Ho",
    University: "Concordia University",
    img: imageToBuffer(".photos/Sharon-Ho.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/sharon-ho/",
    twitter: "",
    email: "",
  },
  {
    name: "Amanda Kolopanis",
    username: "Amanda Kolopanis",
    password: "Amanda Kolopanis",
    University: "Concordia University",
    img: imageToBuffer("./photos/Amanda-Kolopanis.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/amanda-kolopanis/",
    twitter: "",
    email: "",
  },
  {
    name: "Mohayeminul Islam",
    username: "Mohayeminul Islam",
    password: "Mohayeminul Islam",
    University: "University of Alberta",
    img: imageToBuffer("./photos/mohayeminul-islam.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/mohayemin/",
    twitter: "",
    email: "",
  },
  {
    name: "Akalanka Galappaththi",
    username: "Akalanka Galappaththi",
    password: "Akalanka Galappaththi",
    University: "University of Alberta",
    img: imageToBuffer("./photos/Akalanka-Galappaththi.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/akalanka-galappaththi-67580719/",
    twitter: "https://twitter.com/boney_ag",
    email: "akalanka@ualberta.ca",
  },
  {
    name: "Aurel Lucrich Ikama Honey",
    username: "Aurel Lucrich Ikama Honey",
    password: "Aurel Lucrich Ikama Honey",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Aurel-Lucrich-Ikama-Honey.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/aurel-i-345a91ba/",
    twitter: "",
    email: "",
  },
  {
    name: "Pierre-Olivier Cote",
    username: "Pierre-Olivier Cote",
    password: "Pierre-Olivier Cote",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Pierre-Olivier-Cote.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/pierre-olivier-c%C3%B4t%C3%A9/",
    twitter: "",
    email: "",
  },
  {
    name: "Vahid Majdinasab",
    username: "Vahid Majdinasab",
    password: "Vahid Majdinasab",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Vahid-Majdinasab.jpg"),
    website: "",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Patrick Loic Foalem",
    username: "Patrick Loic Foalem",
    password: "Patrick Loic Foalem",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Patrick-Loic-Foalem.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/patrick-loïc-foalem-37281a100",
    twitter: "https://twitter.com/Patrick_Loic_F",
    email: "",
  },
  {
    name: "Forough Majidi",
    username: "Forough Majidi",
    password: "Forough Majidi",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Forough-Majidi.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/forough-majidi-8a35b8227",
    twitter: "",
    email: "",
  },
  {
    name: "Chunli Yu",
    username: "Chunli Yu",
    password: "Chunli Yu",
    University: "Queen's University",
    img: imageToBuffer("./photos/Chunli-Yu.jpg"),
    website: "",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Divya Kamath",
    username: "Divya Kamath",
    password: "Divya Kamath",
    University: "Queen's University",
    img: imageToBuffer("./photos/David- ab.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/divyamkamath/",
    twitter: "",
    email: "",
  },
  {
    name: "Antonio Collante",
    username: "Antonio Collante",
    password: "Antonio Collante",
    University: "Concordia University",
    img: imageToBuffer("./photos/Antonio-Collante.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/antonio-c-737aa566/",
    twitter: "",
    email: "",
  },
  {
    name: "Khaled Badran",
    username: "Khaled Badran",
    password: "Khaled Badran",
    University: "Concordia University",
    img: imageToBuffer("./photos/Khaled-Badran.jpg"),
    website: "https://das.encs.concordia.ca/members/khaled-badran",
    linkedin: "https://www.linkedin.com/in/khaled-badran-6b0908174/",
    twitter: "https://twitter.com/khaled_badran9",
    email: "",
  },
  {
    name: "Rached Bouchoucha",
    username: "Rached Bouchoucha",
    password: "Rached Bouchoucha",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Rached-Bouchoucha.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/rached-bouchoucha-1061997/",
    twitter: "",
    email: "",
  },
  {
    name: "Ahmed Haj Yahmed",
    username: "Ahmed Haj Yahmed",
    password: "Ahmed Haj Yahmed",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Ahmed-Haj-Yahmed.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/ahmed-haj-yahmed/",
    twitter: "",
    email: "",
  },
  {
    name: "Musfiqur Rahman",
    username: "Musfiqur Rahman",
    password: "Musfiqur Rahman",
    University: "Concordia University",
    img: imageToBuffer("./photos/Musfiqur-Rahman.jpg"),
    website: "https://das.encs.concordia.ca/members/musfiqur-rahman",
    linkedin: "https://www.linkedin.com/in/musfiqur-rahman-37596444/",
    twitter: "",
    email: "",
  },
  {
    name: "Jasmine Latendresse",
    username: "Jasmine Latendresse",
    password: "Jasmine Latendresse",
    University: "Concordia University",
    img: imageToBuffer("./photos/Jasmine-Latendresse.jpg"),
    website: "https://jaslatendresse.github.io/",
    linkedin: "https://www.linkedin.com/in/jasmine-latendresse-2835561a6/",
    twitter: "",
    email: "",
  },
  {
    name: "Jiawen Liu",
    username: "Jiawen Liu",
    password: "Jiawen Liu",
    University: "Queen's University",
    img: imageToBuffer("./photos/Jiawen-Liu.jpg"),
    website: "https://seal-queensu.github.io/member-current.html",
    linkedin: "https://www.linkedin.com/in/jiawen-liu-691906178/",
    twitter: "",
    email: "",
  },
  {
    name: "Pouya Fathollahzadeh",
    username: "Pouya Fathollahzadeh",
    password: "Pouya Fathollahzadeh",
    University: "Queen's University",
    img: imageToBuffer("./photos/Pouya-Fathollahzadeh.jpg"),
    website: "https://seal-queensu.github.io/member-current.html",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Akshat Malik",
    username: "Akshat Malik",
    password: "Akshat Malik",
    University: "Queen's University",
    img: imageToBuffer("./photos/Akshat-Malik.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/akshat-malik/",
    twitter: "",
    email: "",
  },
  {
    name: "Harsh Patel",
    username: "Harsh Patel",
    password: "Harsh Patel",
    University: "Queen's University",
    img: imageToBuffer("./photos/Harsh-Patel.jpg"),
    website: "https://alacrity.dev/",
    linkedin: "https://www.linkedin.com/in/harsh8398/",
    twitter: "",
    email: "",
  },
  {
    name: "Jaskirat Singh",
    username: "Jaskirat Singh",
    password: "Jaskirat Singh",
    University: "Queen's University",
    img: imageToBuffer("./photos/Jaskirat-Singh.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/jaskirat409/",
    twitter: "",
    email: "",
  },
  {
    name: "Shenyu Zheng",
    username: "Shenyu Zheng",
    password: "Shenyu Zheng",
    University: "Queen's University",
    img: imageToBuffer("./photos/Shenyu-Zheng.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/shenyu-zheng-31146524b/",
    twitter: "",
    email: "",
  },
  {
    name: "Afiya Fahmida Sarah",
    username: "Afiya Fahmida Sarah",
    password: "Afiya Fahmida Sarah",
    University: "University of Alberta",
    img: imageToBuffer("./photos/Afiya-Fahmida-Sarah.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/afiya-sarah-039007179",
    twitter: "",
    email: "afiya-sarah-039007179",
  },
  {
    name: "Fazle Rabbi",
    username: "Fazle Rabbi",
    password: "Fazle Rabbi",
    University: "Concordia University",
    img: imageToBuffer("./photos/Fazle-Rabbi.jpg"),
    website: "https://frabbisw.github.io/",
    linkedin: "https://www.linkedin.com/in/fazle-rabbi-720139207/",
    twitter: "",
    email: "",
  },
  {
    name: "Lorena Pacheco",
    username: "Lorena Pacheco",
    password: "Lorena Pacheco",
    University: "Concordia University",
    img: imageToBuffer("./photos/Lorena-Pacheco.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/lorenasimedo/",
    twitter: "",
    email: "",
  },
  {
    name: "Samuel Abedu",
    username: "Samuel Abedu",
    password: "Samuel Abedu",
    University: "Concordia University",
    img: imageToBuffer("./photos/Samuel-Abedu.jpg"),
    website: "",
    linkedin: "https://linkedin.com/in/samuel-abedu-42b755103/",
    twitter: "",
    email: "",
  },
  {
    name: "Khouloud Oueslati",
    username: "Khouloud Oueslati",
    password: "Khouloud Oueslati",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Khouloud-Oueslati.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/khouloud-ouesleti/",
    twitter: "",
    email: "",
  },
  {
    name: "Yang Liu",
    username: "Yang Liu",
    password: "Yang Liu",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Yang-Liu.jpg"),
    website: "",
    linkedin: "",
    twitter: "",
    email: "",
  },
  {
    name: "Laila Mahmoud Daw Abodinar",
    username: "Laila Mahmoud Daw Abodinar",
    password: "Laila Mahmoud Daw Abodinar",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Laila-Mahmoud Daw-Abodinar.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/laila-abodinar-2541491ba/",
    twitter: "",
    email: "",
  },
  {
    name: "Altaf Allah Abbassi",
    username: "Altaf Allah Abbassi",
    password: "Altaf Allah Abbassi",
    University: "Ecole Polytechnique",
    img: imageToBuffer("./photos/Altaf-Allah-Abbassi.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/altafallahabbassi/",
    twitter: "",
    email: "",
  },
  {
    name: "Alor Ebube",
    username: "Alor Ebube",
    password: "Alor Ebube",
    University: "Concordia University",
    img: imageToBuffer("./photos/Alor-Ebube.jpg"),
    website: "https://das.encs.concordia.ca/members/alor-ebube",
    linkedin: "https://www.linkedin.com/in/alor-ebubechukwu//",
    twitter: "",
    email: "",
  },
  {
    name: "Mayra Ruiz",
    username: "ayra Ruiz",
    password: "ayra Ruiz",
    University: "Concordia University",
    img: imageToBuffer("./photos/Mayra-Ruiz.jpg"),
    website: "",
    linkedin: "https://www.linkedin.com/in/mruiz27/",
    twitter: "",
    email: "",
  },
];
module.exports = { userData, userDataMembers };
